#+TITLE: SQL Murder Mystery
#+DATE: <2019-12-16, Mon>
#+DESCRIPTION: In this blog post, I'll be discussing a very fun interactive game for learning SQL called 'SQL Murder Mystery'.

I've wanted to get better at my SQL querying skills, but haven't found the time to build an application to learn all the different ways to write SQL queries. Luckily this [[https://news.ycombinator.com/item?id=21799988][post]] on Hackernews showed up and I immediately found myself looking through SQLite docs. The online game, called [[https://mystery.knightlab.com/][SQL Murder Mystery]], utilizies your SQL querying abilities to solve a "whodunnit" murder mystery with only a single clue to start with.

I had a blast working through this game! I always felt that being a softare developer feels like being a detective in a crime novel. In the InfoSec industry there is a game called [[https://trailofbits.github.io/ctf/][Capture the Flag]] that requires players to gain entry into a secure computer. I would love to see more games like this that require learning and exploring different programming languages, runtimes, databases, etc.

** Solutions

*Find Report query*:
#+begin_src sql
select * from crime_scene_report
where
  date = 20180115
  and city = "SQL City"
  and type = "murder"
#+end_src

*Results*:
| date | type | description  | city |
|---+---+---+---+---|
| 20180115 | murder | Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave". | SQL City |

*Find Morty Query*:

#+begin_src sql
select
  person.id,
  person.name,
  interview.transcript
from person
inner join drivers_license on person.license_id=drivers_license.id
inner join interview on person.id=interview.person_id
where person.address_street_name = "Northwestern Dr"
order by person.address_number desc
limit 1
#+end_src

*Results*
| id | name  | transcript |
|---+---+---+---|
| 14887	| Morty Schapiro | I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".           |

*Annabel query*:

#+begin_src sql
select
  person.id,
  person.name,
  interview.transcript
from person
inner join drivers_license on person.license_id=drivers_license.id
inner join interview on person.id=interview.person_id
inner join get_fit_now_member on person.id=get_fit_now_member.person_id
where person.name like "Annabel%" and person.address_street_name = "Franklin Ave"
#+end_src

*Results*
| id | name  | transcript |
|---+---+---+---|
| 16371 | Annabel Miller | I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th.                   |

*Find Suspect query*:

#+begin_src sql
select 
  person.id,
  person.name,
  interview.transcript
from get_fit_now_check_in
inner join get_fit_now_member on get_fit_now_check_in.membership_id=get_fit_now_member.id
inner join person on get_fit_now_member.person_id=person.id
inner join drivers_license on drivers_license.id=person.license_id
inner join interview on interview.person_id=person.id
where
  get_fit_now_check_in.check_in_date = 20180109
  and get_fit_now_check_in.membership_id like "%48Z%"
  and drivers_license.plate_number like "%H42W%"
order by get_fit_now_check_in.check_in_time desc
#+end_src

*Results*
| id | name | transcript |
|---+---+---+---|
| 67318 | Jeremy Bowers	| I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" (65") or 5'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017. |

*Find Real Culprit query*:

#+begin_src sql
select
  person.id,
  person.name,
  facebook_event_checkin.event_name,
  facebook_event_checkin.date
from drivers_license
inner join person on person.license_id=drivers_license.id
inner join facebook_event_checkin on facebook_event_checkin.person_id=person.id
where
  height between 65 and 67
  and hair_color = "red"
  and car_make   = "Tesla"
  and car_model  = "Model S"
limit 1
#+end_src

*Results*
| id | name | event_name | date |
|---+---+---+---|
| 99716 | Miranda Priestly | SQL Symphony Concert | 20171206 |
