#+TITLE: CV
#+DATE: <2019-09-10 Mon>
#+DESCRIPTION: TJ Maynes CV.

* TJ Maynes

- New York, NY
- [[mailto:tjmaynes@gmail.com][tjmaynes@gmail.com]]
- [[https://tjmaynes.com][https://tjmaynes.com]]
- [[https://github.com/tjmaynes][https://github.com/tjmaynes]]
- [[https://linkedin.com/in/tjmaynes][https://linkedin.com/in/tjmaynes]]
- [[https://twitter.com/tjmaynes][https://twitter.com/tjmaynes]]

** Summary
- Polyglot Programmer, Agile Software Developer, Pair Programmer, Test-Driven Development, AWS
- Business Development, Blogging, Filmmaking, Photography

** Professional Experience
- [[http://www.nbcuniversal.com][NBCUniversal Media, LLC]] - *Software Engineer II* - December 2016 to Present
  - Pair programmed and test-drove a Clojure-based microservice that automated the manual input of metadata across thousands of programs which resulted in saving our business unit millions of dollars. The service was deployed on AWS ECS and used AWS RDS and Elasticsearch services.
  - Test-drove a ReactJS-based website to enable Spanish and English-speaking World Cup viewers to watch authenticated World Cup games on Telemundo which resulted in millions of these users being informed with ways to watch the final series of World Cup games. The website was built using server-side rendering via an ExpressJS backend and deployed on AWS ECS.
  - Pair programmed and test-drove an Elixir-based Backend-for-Frontend (BFF) service for our iOS team which resulted in more feature development, faster release cycles and a simpler iOS architecture. The service was deployed on AWS ECS and used AWS RDS and API Gateway.
  - Other backend services that we implemented and managed used microservices patterns and Continuous Deployment practices, including setting up automated tests and pipelines for deploying our microservices to AWS ECS using custom tools built in-house.
- [[https://www.rejuvenan.com][Rejuvenan Global Health, Inc]] - *Software Engineer* - May 2015 to December 2016
  - Responsible for building the Rejuvenan iOS application, writing automation scripts, and contributing code to our company website and backend services. Setup a continuous integration pipeline using Travis-CI and Fastlane for our iOS projects, jobs included kicking off unit tests and new build artifacts from master.
  - Added new features to a growing Ruby-on-Rails backend, which included unit and integration tests. Maintained older backend services written in Java (Spring Framework), including adding a feature to push logs to an AWS S3 bucket and writing unit tests.
- [[https://spatialnetworks.com][Spatial Networks Inc]] - *Web Developer Intern* - February 2013 to August 2013
  - Assisted in the development of a geographical data collection web application.
  - Debugged and fixed front-end UI/UX issues.
  - Started development on an Admin dashboard using Coffeescript and D3js.

** Skills
- Languages
  - Javascript, Go, Python
- Practices
  - Agile methodology, pair programming, test-driven development, consulting, continuous integration and delivery, continuous learning, monitoring, automated testing including unit/integration, performance and consumer-driven contract testing.
- Patterns
  - Clean architecture, dependency injection, strangler, functional programming, composition over inheritence, SOLID, and railway-oriented programming with Either and Maybe monads.
- Technologies
  - Kubernetes, NodeJS, React, SQL/MongoDB, StatsD, Docker, Make, Shell scripts, Jest/Mocha/Chai, OAuth2, Gatling tests, Cookiecutter templates, Elasticsearch/Kibana, Prometheus/Grafana, AWS Cloudformation/ECS/RDS/S3/API Gateway, Azure App Services/DevOps Pipelines/CosmosDB.

** Education
- Bachelor of Science in Computer Science degree (B.S.CS)
  - University of South Florida (Tampa) - May 2015
  - Completed Courses
    - Analysis of Algorithms, Data Structures, Object-Oriented Programming, Software Testing, Operating Systems, Advanced Discrete Structures, Web Apps Design
  - Projects
    - CannyBot - *Team Member* - February 2015 to May 2015
      - Programming the NAO Robot to draw shapes that it "sees" using the Python programming language and OpenCV. Concepts such as edge detection, pixel position interpolation, and forward kinematics were implemented in this project.
    - Senior Project - *Team Leader* - August 2014 to May 2015
      - Developed and delivered a video streaming application using C++, OpenCV, and OpenGL. Worked with a small team of students, managed communications between customer and team members, and built a Gantt Chart for keeping up with project tasks/milestones.
- Associates of Arts (A.S)
  - St. Petersburg College (Tarpon Springs) - July 2013
  - Completed Courses
    - Applied Ethics, Public Speaking, Business Writing, Introduction to Philosophy, General Psychology

** Production Experience
- [[http://http://www.imdb.com/title/tt2751310][Sex Ed]] - *Digital Image Technician* - July to August 2013
  - Responsible for the coordination of the internal workings of the digital camera, archive and manage the digital data, create compressed dailies from raw footage and prepare all digital images for post-production.
- [[http://www.imdb.com/title/tt1236254][Wind Walkers]] - *Grip/Art Department* - November to December 2013
  - Responsible for building and maintaining all the equipment that supports cameras. This equipment, which includes tripods, dollies, tracks, jibs, cranes, and static rigs, is constructed of delicate yet heavy duty parts requiring a high level of experience to operate and move.
- [[http://www.imdb.com/title/tt2339064][Chu and Blossom]] - *Grip/Electric* - July to August 2012
  - Responsible for building and maintaining all the equipment that supports cameras. This equipment, which includes tripods, dollies, tracks, jibs, cranes, and static rigs, is constructed of delicate yet heavy duty parts requiring a high level of experience to operate and move.
- [[http://www.imdb.com/title/tt3268422][Edge of the Woods]] - *Production Assistent* - March 2012
  - Set PAs work on the physical set of the production, whether on location or on a sound stage. Duties include echoing (calling out) "rolls" and "cuts", locking up (making sure nothing interferes with a take), wrangling talent (actors) and background, facilitating communication between departments, distributing paperwork and radios, and related tasks as mandated by the ADs.

** Organizations
- [[http://www.atpi.org][Association of Texas Photography Instructors]] - *Volunteer* - February 2011 to Present
  - Worked alongside teachers and members of various high-school journalism organizations to help educate and promote photojournalism to high school students. Also, helped organize events and provide assistance where needed.
- [[https://sc.edu/study/colleges_schools/cic/journalism_and_mass_communications/scholastic_organizations/sipa/index.php][Southern Interscholastic Press Association]] - *Volunteer* - March 2008 to March 2012
  - Worked alongside teachers and members of various high-school journalism organizations to help educate and promote photojournalism to high school students. Also, helped organize events and provide assistance where needed.
