#+TITLE: Transitioning into Filmmaking
#+DATE: <2019-08-29 Sun>

I was going to write about this as a private journal entry, but decided to write this as a blog post instead. Maybe somebody will read this and find some inspiration to go after their dreams.

I've been interested in filmmaking since as far back as I can remember. I tell people, usually collegues or fellow film lovers, that at one point in my life (during college) I got to work on a few movies. These movies in a way were my film school. Even though I graduated from college with a Computer Science degree, I've always wanted to somehow work in the film industry. Maybe I could use my software skills to help get me there.

So far I've been ignoring these desires in pursuit of getting further programming experience. I've had so much fun and met some pretty amazing people while on this software journey, but that /lingering/ feeling keeps coming back. This desire usually comes up when I go to a Director Q/A session, seeing some great movie, or just walking around New York.

In an effort to transition closer and closer into filmmaking, I've been reading more books and watching movies in that "I'd been meaning to watch but never really got to" category. I just finished [[https://www.imdb.com/name/nm0000691/][John Water's]] [[https://www.goodreads.com/book/show/41940334-mr-know-it-all][/Mr.Know-It-All/]] and currently in the /Blue Velvet/ years of the book of David Lynch interviews, [[https://www.goodreads.com/book/show/80195.Lynch_on_Lynch][Lynch on Lynch]]. I'm also reading [[https://en.wikipedia.org/wiki/Duplass_Brothers_Productions][The Duplass Brothers']] [[https://www.goodreads.com/book/show/35134233-like-brothers][Like Brothers]] book, which has been a fanstastic read. It reads like they are talking directly at you and you learn a lot about how the Brothers think through their problems. I found the chapter where they discuss their "$5 Short" approach to getting into filmmaking to be very inspiring.

Most recently, my partner Emily surprised with movie tickets to see [[https://www.imdb.com/title/tt5865326/][The Laundromat]] that included a Director/Co-Writer Q/A session after the movie. I enjoyed the movie and I got to talk a little with co-writer, Chris Z. Burns, and Steven Soderbergh. Mostly asking questions regarding editing and pulling together certain scenes. I was overwhelmed with how nice and generous they were with their responses.

In an effort to stay focused, and not give up on my filmmaking dreams, I'm surrounding myself with more positive people and writing every day. I hope to start putting on some short films here soon, maybe just shot with my iPhone. I'll keep you posted.
