#+TITLE: Test-Driven Learning
#+DATE: <2020-01-24, Mon>
#+DESCRIPTION: In this blog post, I'll be discussing a strategy I use for rapidly learning a new programming language/library/tool that utilizes a test suite as a feedback tool.

I just wanted to discuss an approach I use to learn new programming languages, runtimes, libraries and/or implementing abstract concepts. The approach is essentially test-driven development, but instead of writing tests as a feedback mechanism for refactoring code, we are writing tests as a feedback mechanism for learning. Let's call this "Test-Driven Learning" for now. This test-driven learning approach gives us a quick feedback loop (via test-runner) and sandbox environment (via test-suite), that we can use for rapidly learning new concepts.

The test-driven learning approach is similiar to using a REPL (Read-Evaluate-Print-Loop) to learning new concepts. However, I've found using most REPL environments (minus Emacs + Lisp setup) can feel too constraining to driven out building DSLs, learning new libraries, etc. Also, depending on the language you are learning, there may not be a REPL easily, if not at all, available to learn from.

To implement test-driven learning, you will need to find a testing framework for the language you are trying to learn.

** Testing Frameworks

Testing frameworks are usually available in every language/runtime, it's just a matter of finding one that is well supported by the respected language community. For instance, in the [[https://www.ruby-lang.org/en/community/weblogs/][Ruby]] community, [[https://rspec.info/][RSpec]] is a very popular testing framework that you'll find in many Ruby projects. Since this particular community uses this testing framework, you should have confidence that you'll be able to find blog posts and other forms of documentation for times you feel stuck or want to do different kinds of testing.

#+begin_src
Pro Tip: Researching what the programming language community is using for testing frameworks is also a good opportunity to learn more from people that have experience building software with said language. You can usually find these communities on different online forums like Google Groups, Slack, Twitter or with a quick [[][Duck-Duck-Go]] search.
#+end_src

Assuming you have chosen a testing-framework, and you have the language runtime installed on your machine, your next step is fire up your favorite text-editor, or IDE, and write your test file.
